name: Docker iTron MQTT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: dockerfile=docker/Dockerfile, docker build -t xcel_itron2mqtt -f ${dockerfile} .

